module.exports = {
    contact: {
        firstName: "Clouvis",
        lastName: "Denosta",
        name: "",
        taxID: "",
        email: "clouvisd@gmail.com",
        country: "US",
        state: "AZ",
        city: "Phoenix",
        address1: "6220 W HEDGEHOG PL",
        addressType: "home",
        organization: "Enigma",
        organization1: "Enigma Fire & Casualty",
        producerCode: "ProducerCode:3"
    },
    accountName: "",
    contactType: "",
    accountNumber: "",
    vehicleVin: ["WDDHF8JB3CA549096","4V4VDBJG8TN730171"],
    policyNumber: "",
    effectiveDate: "",
    drivers: [],
    driverFirstName: ['Yen', 'Christine'],
    driverLastName: ['Bico','Vergara'],
    dateOfBirth: ['06/10/2000', '08/06/1990'],
    maritalStatus: ['Single','Single'],
    addressLine: ['1827 W NEW RIVER RD','7007 W INDIAN SCHOOL RD'],
    city: ['PHOENIX','MESA'],
    state: ['Arizona','Arizona'],
    zipCode: ['85209', '85210'],
    addressType: ['Home','Home'],
    licenseNumber: ['D02267767','D03841206'],
    licenseState: ['Arizona','Arizona'],
    yearLicensed: ['2000', '2002'],
    numberOfAccidentsPolicyLevel: ['1','0'],
    numberOfViolationsPolicyLevel: ['1','0'],
    numberOfAccidentsAccountLevel: ['1','0'],
    numberOfViolationsAccountLevel: ['1','0'],
    costNew: ['10000','20000'],
    licenseStateInVehicle: ['Arizona','Arizona'],
    lossDate: "",
    claim: {
        claimDescription: "test",
        lossDate: ""
    },

    lOB: "Personal Auto",
    vehicle: [],
    questions: ["Do/Have past, present, or discontinued operations involve(d) storing, treating, discharging, applying, disposing or transporting of hazardous material? (e.g. landfills, wastes, fuel tanks, etc)", "Is there a labor interchange with any other business/subsidiary?", "Any tax liens or bankruptcy within the last 5 years?"],
    permission: "",
    permissionFindResult: "false",
    user: "",
    accountFirstname: "",
    accountLastname: ""
};